spring.application.name=CourseRegistersation
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3305/iagami
spring.datasource.username = root
spring.datasource.password = 54325
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
